version: '3.8'

services:

  front:
    build:
      context: ../rental-girlfriend-frontend # Context is the 'folder_b' (frontend) folder
      dockerfile: ../rental-girlfriend-frontend/Dockerfile # Path to Dockerfile.dev
    container_name: front
    restart: unless-stopped
    env_file:
      - ../rental-girlfriend-frontend/.env

  api:
    build: .
    container_name: api
    restart: unless-stopped
    env_file:
      - ./config/.env

  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"   # Expose port 80 on the EC2 server
      - "443:443" # (Optional) Expose port 443 for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro